name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up SSH key for access to the VPS
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Ensure SSH key is available and print debug info
      - name: Debug SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          cat private_key.pem

      # Step 4: Add the VPS's SSH fingerprint to the known hosts
      - name: Add VPS to known hosts
        run: |
          ssh-keyscan -H your_vps_ip >> ~/.ssh/known_hosts

      # Step 5: Deploy to VPS
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem user@your_vps_ip "cd /path/to/your/project && git pull origin main && ./deploy_script.sh"
